name: clsswjz
description: App for clsswjz-server

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  intl: ^0.19.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2
  path: ^1.8.3
  universal_html: ^2.2.4
  dio: ^5.4.0
  flutter_slidable: ^3.0.1
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^27.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  http: ^0.13.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/logo.png

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true
  web:
    generate: true
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    icon_size: 256 # 可选，默认 48
  linux:
    generate: true
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"
