name: Build and Release Flutter App

on:
  push:
    tags:
      - "v*" # 触发规则：每次推送以 v 开头的 tag 时运行

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [apk, windows, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        if: matrix.platform == 'apk'
        run: flutter build apk --release

      - name: Build Windows
        if: matrix.platform == 'windows'
        run: flutter build windows --release

      - name: Build Linux
        if: matrix.platform == 'linux'
        run: flutter build linux --release

      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-release
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/windows/runner/Release/
            build/linux/release/bundle/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.platform }}-release

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automatic release of Flutter binaries for platform: ${{ matrix.platform }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ matrix.platform }}-release
          asset_name: ${{ matrix.platform }}-release.zip
          asset_content_type: application/zip
